# name: JS Actions

# on: [push]

# jobs:
#   action:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
    
#     - name: hello-actions
#       uses: ./.github/actions/hello-world
      
