name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: ha-ha
        id: jokes
        uses: ./.github/actions/joke-act

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
            joke: ${{steps.jokes.outputs.joke-output}}
            repo-token: ${{secrets.GITHUB_TOKEN}}
